# -*- coding: utf-8 -*-
"""Store Sales Analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iMYbPgOsCrD0HL5MNwL0LAkr1OXFlV9u
"""



# ============================================================
# PROJECT 2 — Sales Data Analyzer
# Author   : Shabana Malik
# Purpose  : Analyze 12 months sales data of 3 products
#            to help a store understand its business
# Concepts : random, sum, argmax, cumsum,
#            where, reshape, broadcasting
# ============================================================

import numpy as np

# ------------------------------------------------------------
# STEP 1 — Create Fake Sales Data
# seed(3)     : makes sure we get same random numbers every time
# randint     : generates random numbers between 50 and 300
# size=(3,12) : 3 products (rows) x 12 months (columns)
# ------------------------------------------------------------
np.random.seed(3)
sales = np.random.randint(50, 300, size=(3, 12))

products = ['Product A', 'Product B', 'Product C']
months   = ['Jan','Feb','Mar','Apr','May','Jun',
            'Jul','Aug','Sep','Oct','Nov','Dec']

print("=" * 50)
print("         SALES DATA ANALYZER")
print("=" * 50)
print("Sales of 3 Products for 12 Months (in K):")
print(sales)

# ------------------------------------------------------------
# STEP 2 — Calculate Annual Sales Per Product
# axis=1 : move along each row (product wise)
# zip    : loop through products and totals together
# ------------------------------------------------------------
Annual = np.sum(sales, axis=1)
print("-" * 50)
print("Annual Sales Per Product:")
for p, r in zip(products, Annual):
    print(f"  {p} : {r}K")

# ------------------------------------------------------------
# STEP 3 — Find the Best Month
# axis=0  : move along each column (month wise)
# argmax  : returns index of the highest value
# months[]: use index to get month name
# ------------------------------------------------------------
Total_by_month = np.sum(sales, axis=0)
Best_month     = np.argmax(Total_by_month)
print("-" * 50)
print("Monthly Totals  :", Total_by_month)
print(f"Best Month Overall: {months[Best_month]}")

# ------------------------------------------------------------
# STEP 4 — Cumulative (Running) Sales of Product A
# sales[0] : select only Product A data (first row)
# cumsum   : adds up sales month by month
#            Jan=150, Feb=150+200=350, Mar=350+180=530 ...
# ------------------------------------------------------------
cum = np.cumsum(sales[0])
print("-" * 50)
print("Running Total of Product A:")
for i in range(len(Months)):
    print(f"  {months[i]} : {cum[i]}K")

# ------------------------------------------------------------
# STEP 5 — Find High Sales Months
# np.where(sales > 200) : finds all values above 200K
# len(High[0])          : counts how many such months exist
# ------------------------------------------------------------
High = np.where(sales > 200)
print("-" * 50)
print(f"Total Months with Sales above 200K: {len(High[0])}")

# ------------------------------------------------------------
# STEP 6 — Calculate Sales After Tax (Broadcasting)
# multiplying entire array by 0.90 deducts 10% tax
# NumPy applies this to every value automatically
# this is called broadcasting
# ------------------------------------------------------------
After_tax = sales * 0.90
print("-" * 50)
print("Sales After 10% Tax Deduction (in K):")
print(After_tax)

# ------------------------------------------------------------
# STEP 7 — Generate Quarterly Report
# reshape(3,4,3) : split into 3 products, 4 quarters, 3 months
# sum(axis=2)    : add the 3 months inside each quarter
# final shape    : (3,4) = 3 products x 4 quarters
# ------------------------------------------------------------
Quarterly = sales.reshape(3, 4, 3).sum(axis=2)
print("-" * 50)
print("Quarterly Sales Report:")
print(f"{'':15}  Q1     Q2     Q3     Q4")
for i, p in enumerate(products):
    q = Quarterly[i]
    print(f"  {p} :  {q[0]}K   {q[1]}K   {q[2]}K   {q[3]}K")

print("=" * 50)
print("Analysis Complete!")
print("=" * 50)