# -*- coding: utf-8 -*-
"""student_marks_analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fVATOK9V4Cjtb7OAmrQ1s1ZVloK-Um04

**Project: Student Marks Analyzer**
*NumPy Mini Project*

**Problem Statement:**

You are given marks of 10 students in 3 subjects (Math, Science, English). Using NumPy, solve the following:

1. Create a 2D NumPy array of 10 students with marks in 3 subjects
2. Calculate each student's average marks and the overall class average
3. Find the highest scoring student and display their marks
4. Find all failed students — those who scored below 40 in any subject
5. Assign grades to each student based on their average:
   - 80 and above → A
   - 60 and above → B
   - 40 and above → C
   - Below 40 → F

**NumPy concepts used:**
`np.array` · `np.mean` · `np.argmax` · `np.any` · `np.where` · `np.select` · boolean indexing · axis parameter · 2D arrays

# ================================
# Project: Student Marks Analyzer
# Topics:  NumPy 2D arrays, mean, argmax,
#          boolean indexing, np.select
# ================================
"""

#1.Create a 2D NumPy array of 10 students with marks in 3 subjects
import numpy as np
marks=np.array([[80,70,40],
            [67,87,58],
            [76,89,74],
            [49,83,29],
            [54,66,78],
            [78,98,45],
            [88,90,65],
            [34,67,89],
            [76,88,98],
            [43,25,76]])
print(f"Shape of an array: {marks.shape}")
print(marks)
print("─"*40)

#2.Calculate each student's average marks and the overall class average
student_avg=np.mean(marks, axis=1)       # average of every student
class_avg=np.mean(marks)                # class average
for i,avg in enumerate(student_avg):
    print(f'student {i+1} : {avg:.2f}')
print("Class overall agerage :", round(class_avg, 2))
print("─"*40)

#3.Find the highest scoring student and display their marks
Top_index=np.argmax(student_avg)
print("Highest score : Student",Top_index+1)
print("Higest marks :",marks[Top_index])
print("─"*40)

#4.Find all failed students — those who scored below 40 in any subject
Failed_marks=np.any(marks < 40,axis=1)
Failed_students=np.where(Failed_marks)[0]
print("Failed Students:",Failed_students+1)
print("─"*40)

# Assign grades to each student based on their average:
# 80 and above → A
# 60 and above → B
# 40 and above → C
# Below 40 → F
conditions=[student_avg>=80,
            student_avg>=60,
            student_avg>=40,]
Grades=np.select(conditions,['A','B','C'],default='F')
for i,(avg,Grades) in enumerate(zip(student_avg,Grades)):
    print(f'student {i+1}: avg = {avg:.2f}  grade= {Grades}')
print("─"*40)

